name: Build on PR

on: 
  pull_request:
    branches:
      - main  # Fixed spacing issue

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3  # Fixed syntax
      - name: Use Node.js  # Fixed syntax
        uses: actions/setup-node@v3
        with: 
          node-version: '20'

      - name: Install dependencies  # Fixed syntax
        run: npm install

      - name: Generate Prisma Client
        run: npm run db:generate

      - name: Run Build  # Fixed syntax
        run: npm run build
